### ISSUE TITLE
regarding 3d pipelines

### ISSUE THREAD

**Issue by SadhakAkshay** [Gaia3D/mago-3d-tiler#18]
Hello,
I am trying to use latest released version v1.7.0 to generate 3d tiles for underground pipe utilities, I have shapefile data for pipelines, and I am using following command to generate b3dm 3d tiles from shapefile: -

**root@NTPL-PC-083:/home/rajnish/Desktop/Sanskardham/mago_3d_new_pieline# java -jar mago-3d-tiler-1.7.0-natives-linux.jar -i gas_pipeLines.shp -o output/ -ot b3dm -c 32643**

However it is not generating tiles, what modifications can be done in above command or are there any other modifications on system side that can be done to generate 3d tiles.

**Comment by znkim** [comment]
Hello, @SadhakAkshay 

When I looked at your command, it seems to work fine.
However, I think you need to try a couple of things.
First, try replacing the input path in the `-i` option with an absolute path and run it. 

If that doesn't work, try adding the `-debug` option to see if it causes any issues.

Also, if you can provide logs or data samples, I'll be able to help you further.

Thank you.

**Comment by SadhakAkshay** [comment]
Hello sir,
I tried to provide absolute path in the command for input and output data and I tried with pnts output data type, I also add -debug option in the command, here is the output,

**(base) rajnish@NTPL-PC-083:~$ java -jar /home/rajnish/Desktop/Sanskardham/mago_3d_new_pieline/mago-3d-tiler-1.7.0-natives-linux.jar -i /home/rajnish/Desktop/Sanskardham/mago_3d_new_pieline/gas_pipeLines.shp -ot pnts -o /home/rajnish/Desktop/Sanskardham/mago_3d_new_pieline/output/ -debug**
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
[INFO][12:32:41][mago.Mago3DTilerMain(printStart:73)]::
┳┳┓┏┓┏┓┏┓  ┏┓┳┓  ┏┳┓┳┓ ┏┓┳┓
┃┃┃┣┫┃┓┃┃   ┫┃┃   ┃ ┃┃ ┣ ┣┫
┛ ┗┛┗┗┛┗┛  ┗┛┻┛   ┻ ┻┗┛┗┛┛┗
3d-tiler(1.7.0) by Gaia3d, Inc.
----------------------------------------
[INFO][12:32:41][mago.OptionsCorrector(findInputFormatType:88)]::Auto Selected Format type: SHP
[DEBUG][12:32:41][mago.GlobalOptions(printDebugOptions:330)]::========================================
[DEBUG][12:32:41][mago.GlobalOptions(printDebugOptions:331)]::Input Path: /home/rajnish/Desktop/Sanskardham/mago_3d_new_pieline/gas_pipeLines.shp
[DEBUG][12:32:41][mago.GlobalOptions(printDebugOptions:332)]::Output Path: /home/rajnish/Desktop/Sanskardham/mago_3d_new_pieline/output/
[DEBUG][12:32:41][mago.GlobalOptions(printDebugOptions:333)]::Input Format: SHP
[DEBUG][12:32:41][mago.GlobalOptions(printDebugOptions:334)]::Output Format: PNTS
[DEBUG][12:32:41][mago.GlobalOptions(printDebugOptions:335)]::Terrain File Path: null
[DEBUG][12:32:41][mago.GlobalOptions(printDebugOptions:336)]::Instance File Path: /home/rajnish/Desktop/Sanskardham/mago_3d_new_pieline/gas_pipeLines.shp/instance.dae
[DEBUG][12:32:41][mago.GlobalOptions(printDebugOptions:337)]::Log Path: null
[DEBUG][12:32:41][mago.GlobalOptions(printDebugOptions:338)]::Recursive Path Search: false
[DEBUG][12:32:41][mago.GlobalOptions(printDebugOptions:340)]::========================================
[DEBUG][12:32:41][mago.GlobalOptions(printDebugOptions:341)]::Coordinate Reference System: EPSG:3857
[DEBUG][12:32:41][mago.GlobalOptions(printDebugOptions:342)]::Proj4 Code: null
[DEBUG][12:32:41][mago.GlobalOptions(printDebugOptions:343)]::Minimum LOD: 0
[DEBUG][12:32:41][mago.GlobalOptions(printDebugOptions:344)]::Maximum LOD: 3
[DEBUG][12:32:41][mago.GlobalOptions(printDebugOptions:345)]::Minimum GeometricError: 16
[DEBUG][12:32:41][mago.GlobalOptions(printDebugOptions:346)]::Maximum GeometricError: 2147483647
[DEBUG][12:32:41][mago.GlobalOptions(printDebugOptions:347)]::PointCloud Point Limit: 65536
[DEBUG][12:32:41][mago.GlobalOptions(printDebugOptions:348)]::PointCloud Scale: 2
[DEBUG][12:32:41][mago.GlobalOptions(printDebugOptions:349)]::PointCloud Skip Interval: 4
[DEBUG][12:32:41][mago.GlobalOptions(printDebugOptions:350)]::Debug Mode: true
[DEBUG][12:32:41][mago.GlobalOptions(printDebugOptions:351)]::Debug LOD: false
[DEBUG][12:32:41][mago.GlobalOptions(printDebugOptions:352)]::Debug GLB: false
[DEBUG][12:32:41][mago.GlobalOptions(printDebugOptions:353)]::classicTransformMatrix: false
[DEBUG][12:32:41][mago.GlobalOptions(printDebugOptions:354)]::Multi-Thread Count: 2
[DEBUG][12:32:41][mago.GlobalOptions(printDebugOptions:357)]::========================================
[DEBUG][12:32:41][mago.GlobalOptions(printDebugOptions:358)]::Swap Up-Axis: false
[DEBUG][12:32:41][mago.GlobalOptions(printDebugOptions:359)]::Flip Up-Axis: false
[DEBUG][12:32:41][mago.GlobalOptions(printDebugOptions:360)]::RefineAdd: true
[DEBUG][12:32:41][mago.GlobalOptions(printDebugOptions:361)]::Flip Coordinate: false
[DEBUG][12:32:41][mago.GlobalOptions(printDebugOptions:362)]::Zero Origin: false
[DEBUG][12:32:41][mago.GlobalOptions(printDebugOptions:363)]::Auto Up-Axis: false
[DEBUG][12:32:41][mago.GlobalOptions(printDebugOptions:364)]::Ignore Textures: false
[DEBUG][12:32:41][mago.GlobalOptions(printDebugOptions:365)]::LargeMesh: false
[DEBUG][12:32:41][mago.GlobalOptions(printDebugOptions:368)]::========================================
[DEBUG][12:32:41][mago.GlobalOptions(printDebugOptions:369)]::Name Column: name
[DEBUG][12:32:41][mago.GlobalOptions(printDebugOptions:370)]::Height Column: height
[DEBUG][12:32:41][mago.GlobalOptions(printDebugOptions:371)]::Altitude Column: altitude
[DEBUG][12:32:41][mago.GlobalOptions(printDebugOptions:372)]::Absolute Altitude: 0.0
[DEBUG][12:32:41][mago.GlobalOptions(printDebugOptions:373)]::Minimum Height: 1.0
[DEBUG][12:32:41][mago.GlobalOptions(printDebugOptions:374)]::Skirt Height: 4.0
[DEBUG][12:32:41][mago.GlobalOptions(printDebugOptions:375)]::========================================
[INFO][12:32:41][mago.Mago3DTiler(execute:23)]::Starting process flow: PointCloudProcessModel
[INFO][12:32:41][process.TilingPipeline(createTemp:158)]::[Pre] Created temp directory in /home/rajnish/Desktop/Sanskardham/mago_3d_new_pieline/output/temp
[INFO][12:32:41][process.TilingPipeline(startPreProcesses:64)]::[Pre] Start the pre-processing.
[INFO][12:32:41][process.TilingPipeline(startPreProcesses:68)]::[Pre] Loading all files.
[INFO][12:32:41][process.TilingPipeline(startPreProcesses:70)]::[Pre] Finished loading all files
ERROR: cannot open lasreadershp with file name '/home/rajnish/Desktop/Sanskardham/mago_3d_new_pieline/gas_pipeLines.shp'
[ERROR][12:32:41][process.TilingPipeline(executeThread:179)]::Failed to execute thread.
java.util.concurrent.ExecutionException: java.lang.NullPointerException: Cannot invoke "com.github.mreutegg.laszip4j.laslib.LASreader.inside_none()" because "reader" is null
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:?]
	at java.util.concurrent.FutureTask.get(FutureTask.java:191) ~[?:?]
	at com.gaia3d.process.TilingPipeline.executeThread(TilingPipeline.java:175) [mago-3d-tiler-1.7.0-natives-linux.jar:1.7.0]
	at com.gaia3d.process.TilingPipeline.startPreProcesses(TilingPipeline.java:102) [mago-3d-tiler-1.7.0-natives-linux.jar:1.7.0]
	at com.gaia3d.process.TilingPipeline.process(TilingPipeline.java:50) [mago-3d-tiler-1.7.0-natives-linux.jar:1.7.0]
	at com.gaia3d.command.PointCloudProcessModel.run(PointCloudProcessModel.java:35) [mago-3d-tiler-1.7.0-natives-linux.jar:1.7.0]
	at com.gaia3d.command.mago.Mago3DTiler.execute(Mago3DTiler.java:24) [mago-3d-tiler-1.7.0-natives-linux.jar:1.7.0]
	at com.gaia3d.command.mago.Mago3DTilerMain.main(Mago3DTilerMain.java:55) [mago-3d-tiler-1.7.0-natives-linux.jar:1.7.0]
Caused by: java.lang.NullPointerException: Cannot invoke "com.github.mreutegg.laszip4j.laslib.LASreader.inside_none()" because "reader" is null
	at com.github.mreutegg.laszip4j.LASReader$None.apply(LASReader.java:254) ~[mago-3d-tiler-1.7.0-natives-linux.jar:1.7.0]
	at com.github.mreutegg.laszip4j.LASReader.openReader(LASReader.java:194) ~[mago-3d-tiler-1.7.0-natives-linux.jar:1.7.0]
	at com.github.mreutegg.laszip4j.LASReader.getHeader(LASReader.java:159) ~[mago-3d-tiler-1.7.0-natives-linux.jar:1.7.0]
	at com.gaia3d.converter.pointcloud.LasConverter.convert(LasConverter.java:47) ~[mago-3d-tiler-1.7.0-natives-linux.jar:1.7.0]
	at com.gaia3d.converter.pointcloud.LasConverter.load(LasConverter.java:33) ~[mago-3d-tiler-1.7.0-natives-linux.jar:1.7.0]
	at com.gaia3d.converter.PointCloudFileLoader.loadPointCloud(PointCloudFileLoader.java:29) ~[mago-3d-tiler-1.7.0-natives-linux.jar:1.7.0]
	at com.gaia3d.converter.PointCloudFileLoader.loadTileInfo(PointCloudFileLoader.java:51) ~[mago-3d-tiler-1.7.0-natives-linux.jar:1.7.0]
	at com.gaia3d.process.TilingPipeline.lambda$startPreProcesses$0(TilingPipeline.java:80) ~[mago-3d-tiler-1.7.0-natives-linux.jar:1.7.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Exception in thread "main" java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NullPointerException: Cannot invoke "com.github.mreutegg.laszip4j.laslib.LASreader.inside_none()" because "reader" is null
	at com.gaia3d.process.TilingPipeline.executeThread(TilingPipeline.java:180)
	at com.gaia3d.process.TilingPipeline.startPreProcesses(TilingPipeline.java:102)
	at com.gaia3d.process.TilingPipeline.process(TilingPipeline.java:50)
	at com.gaia3d.command.PointCloudProcessModel.run(PointCloudProcessModel.java:35)
	at com.gaia3d.command.mago.Mago3DTiler.execute(Mago3DTiler.java:24)
	at com.gaia3d.command.mago.Mago3DTilerMain.main(Mago3DTilerMain.java:55)
Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException: Cannot invoke "com.github.mreutegg.laszip4j.laslib.LASreader.inside_none()" because "reader" is null
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at com.gaia3d.process.TilingPipeline.executeThread(TilingPipeline.java:175)
	... 5 more
Caused by: java.lang.NullPointerException: Cannot invoke "com.github.mreutegg.laszip4j.laslib.LASreader.inside_none()" because "reader" is null
	at com.github.mreutegg.laszip4j.LASReader$None.apply(LASReader.java:254)
	at com.github.mreutegg.laszip4j.LASReader.openReader(LASReader.java:194)
	at com.github.mreutegg.laszip4j.LASReader.getHeader(LASReader.java:159)
	at com.gaia3d.converter.pointcloud.LasConverter.convert(LasConverter.java:47)
	at com.gaia3d.converter.pointcloud.LasConverter.load(LasConverter.java:33)
	at com.gaia3d.converter.PointCloudFileLoader.loadPointCloud(PointCloudFileLoader.java:29)
	at com.gaia3d.converter.PointCloudFileLoader.loadTileInfo(PointCloudFileLoader.java:51)
	at com.gaia3d.process.TilingPipeline.lambda$startPreProcesses$0(TilingPipeline.java:80)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

and for b3dm output type i used following command: -
**java -jar /home/rajnish/Desktop/Sanskardham/mago_3d_new_pieline/mago-3d-tiler-1.7.0-natives-linux.jar -i /home/rajnish/Desktop/Sanskardham/mago_3d_new_pieline/gas_pipeLines.shp -ot b3dm -o /home/rajnish/Desktop/Sanskardham/mago_3d_new_pieline/output/ -debug**

although this do not generate any error but in output folder no tiles were generated.

**Comment by znkim** [comment]
Sorry for the delay in responding to your issue.

First, the ``-ot`` option is correct for the ``b3dm`` value you initially ran.
Also, I'm closing this issue because it's similar to the issue below.

link : https://github.com/Gaia3D/mago-3d-tiler/issues/22
