### ISSUE TITLE
input kml output b3dm failed!

### ISSUE THREAD

**Issue by logchen** [Gaia3D/mago-3d-tiler#32]
a@a-ubuntu:~/Downloads/road$ docker run --rm -v "/home/a/Downloads/road:/workspace" gaia3d/mago-3d-tiler:1.9.0 -it kml -i /workspace/kml/ -o /workspace/tiles -d
[INFO][07:43:41][mago.Mago3DTilerMain(printStart:73)]::
┳┳┓┏┓┏┓┏┓  ┏┓┳┓  ┏┳┓┳┓ ┏┓┳┓
┃┃┃┣┫┃┓┃┃   ┫┃┃   ┃ ┃┃ ┣ ┣┫
┛ ┗┛┗┗┛┗┛  ┗┛┻┛   ┻ ┻┗┛┗┛┛┗
3d-tiler(dev-version) by Gaia3D, Inc.
----------------------------------------
[DEBUG][07:43:41][mago.GlobalOptions(printDebugOptions:330)]::========================================
[DEBUG][07:43:41][mago.GlobalOptions(printDebugOptions:331)]::Input Path: /workspace/kml/
[DEBUG][07:43:41][mago.GlobalOptions(printDebugOptions:332)]::Output Path: /workspace/tiles
[DEBUG][07:43:41][mago.GlobalOptions(printDebugOptions:333)]::Input Format: KML
[DEBUG][07:43:41][mago.GlobalOptions(printDebugOptions:334)]::Output Format: B3DM
[DEBUG][07:43:41][mago.GlobalOptions(printDebugOptions:335)]::Terrain File Path: null
[DEBUG][07:43:41][mago.GlobalOptions(printDebugOptions:336)]::Instance File Path: /workspace/kml//instance.dae
[DEBUG][07:43:41][mago.GlobalOptions(printDebugOptions:337)]::Log Path: null
[DEBUG][07:43:41][mago.GlobalOptions(printDebugOptions:338)]::Recursive Path Search: true
[DEBUG][07:43:41][mago.GlobalOptions(printDebugOptions:340)]::========================================
[DEBUG][07:43:41][mago.GlobalOptions(printDebugOptions:341)]::Coordinate Reference System: EPSG:3857
[DEBUG][07:43:41][mago.GlobalOptions(printDebugOptions:342)]::Proj4 Code: null
[DEBUG][07:43:41][mago.GlobalOptions(printDebugOptions:343)]::Minimum LOD: 0
[DEBUG][07:43:41][mago.GlobalOptions(printDebugOptions:344)]::Maximum LOD: 3
[DEBUG][07:43:41][mago.GlobalOptions(printDebugOptions:345)]::Minimum GeometricError: 16
[DEBUG][07:43:41][mago.GlobalOptions(printDebugOptions:346)]::Maximum GeometricError: 2147483647
[DEBUG][07:43:41][mago.GlobalOptions(printDebugOptions:347)]::PointCloud Point Limit: 65536
[DEBUG][07:43:41][mago.GlobalOptions(printDebugOptions:348)]::PointCloud Scale: 2
[DEBUG][07:43:41][mago.GlobalOptions(printDebugOptions:349)]::PointCloud Skip Interval: 4
[DEBUG][07:43:41][mago.GlobalOptions(printDebugOptions:350)]::Debug Mode: true
[DEBUG][07:43:41][mago.GlobalOptions(printDebugOptions:351)]::Debug LOD: false
[DEBUG][07:43:41][mago.GlobalOptions(printDebugOptions:352)]::Debug GLB: false
[DEBUG][07:43:41][mago.GlobalOptions(printDebugOptions:353)]::classicTransformMatrix: false
[DEBUG][07:43:41][mago.GlobalOptions(printDebugOptions:354)]::Multi-Thread Count: 10
[DEBUG][07:43:41][mago.GlobalOptions(printDebugOptions:357)]::========================================
[DEBUG][07:43:41][mago.GlobalOptions(printDebugOptions:358)]::Swap Up-Axis: true
[DEBUG][07:43:41][mago.GlobalOptions(printDebugOptions:359)]::Flip Up-Axis: false
[DEBUG][07:43:41][mago.GlobalOptions(printDebugOptions:360)]::RefineAdd: false
[DEBUG][07:43:41][mago.GlobalOptions(printDebugOptions:361)]::Flip Coordinate: false
[DEBUG][07:43:41][mago.GlobalOptions(printDebugOptions:362)]::Zero Origin: false
[DEBUG][07:43:41][mago.GlobalOptions(printDebugOptions:363)]::Auto Up-Axis: false
[DEBUG][07:43:41][mago.GlobalOptions(printDebugOptions:364)]::Ignore Textures: false
[DEBUG][07:43:41][mago.GlobalOptions(printDebugOptions:365)]::Max Triangles: 524288
[DEBUG][07:43:41][mago.GlobalOptions(printDebugOptions:366)]::Max Instance Size: 512
[DEBUG][07:43:41][mago.GlobalOptions(printDebugOptions:367)]::Max Node Depth: 32
[DEBUG][07:43:41][mago.GlobalOptions(printDebugOptions:368)]::LargeMesh: false
[DEBUG][07:43:41][mago.GlobalOptions(printDebugOptions:371)]::========================================
[DEBUG][07:43:41][mago.GlobalOptions(printDebugOptions:372)]::Name Column: name
[DEBUG][07:43:41][mago.GlobalOptions(printDebugOptions:373)]::Height Column: height
[DEBUG][07:43:41][mago.GlobalOptions(printDebugOptions:374)]::Altitude Column: altitude
[DEBUG][07:43:41][mago.GlobalOptions(printDebugOptions:375)]::Absolute Altitude: 0.0
[DEBUG][07:43:41][mago.GlobalOptions(printDebugOptions:376)]::Minimum Height: 1.0
[DEBUG][07:43:41][mago.GlobalOptions(printDebugOptions:377)]::Skirt Height: 4.0
[DEBUG][07:43:41][mago.GlobalOptions(printDebugOptions:378)]::========================================
[INFO][07:43:41][mago.Mago3DTiler(execute:26)]::Starting process flow: BatchedProcessModel
[INFO][07:43:41][process.TilingPipeline(createTemp:158)]::[Pre] Created temp directory in /workspace/tiles/temp
[INFO][07:43:41][process.TilingPipeline(startPreProcesses:63)]::[Pre] Start the pre-processing.
[INFO][07:43:41][process.TilingPipeline(startPreProcesses:67)]::[Pre] Loading all files.
[INFO][07:43:41][process.TilingPipeline(startPreProcesses:69)]::[Pre] Finished loading all files
[ERROR][07:43:41][assimp.AssimpConverter(load:56)]::File does not exist: /workspace/kml/http:/maps.google.com/mapfiles/kml/pushpin/ylw-pushpin.png
[ERROR][07:43:41][process.TilingPipeline(executeThread:179)]::Failed to execute thread.
java.util.concurrent.ExecutionException: java.lang.RuntimeException: File does not exist: /workspace/kml/http:/maps.google.com/mapfiles/kml/pushpin/ylw-pushpin.png
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:?]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:?]
	at com.gaia3d.process.TilingPipeline.executeThread(TilingPipeline.java:175) [classes/:?]
	at com.gaia3d.process.TilingPipeline.startPreProcesses(TilingPipeline.java:101) [classes/:?]
	at com.gaia3d.process.TilingPipeline.process(TilingPipeline.java:49) [classes/:?]
	at com.gaia3d.command.model.BatchedProcessModel.run(BatchedProcessModel.java:78) [classes/:?]
	at com.gaia3d.command.mago.Mago3DTiler.execute(Mago3DTiler.java:27) [classes/:?]
	at com.gaia3d.command.mago.Mago3DTilerMain.main(Mago3DTilerMain.java:55) [classes/:?]
Caused by: java.lang.RuntimeException: File does not exist: /workspace/kml/http:/maps.google.com/mapfiles/kml/pushpin/ylw-pushpin.png
	at com.gaia3d.converter.assimp.AssimpConverter.load(AssimpConverter.java:57) ~[classes/:?]
	at com.gaia3d.converter.loader.BatchedFileLoader.loadScene(BatchedFileLoader.java:36) ~[classes/:?]
	at com.gaia3d.converter.loader.BatchedFileLoader.loadTileInfo(BatchedFileLoader.java:91) ~[classes/:?]
	at com.gaia3d.process.TilingPipeline.lambda$startPreProcesses$0(TilingPipeline.java:79) ~[classes/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
Exception in thread "main" java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: File does not exist: /workspace/kml/http:/maps.google.com/mapfiles/kml/pushpin/ylw-pushpin.png
	at com.gaia3d.process.TilingPipeline.executeThread(TilingPipeline.java:180)
	at com.gaia3d.process.TilingPipeline.startPreProcesses(TilingPipeline.java:101)
	at com.gaia3d.process.TilingPipeline.process(TilingPipeline.java:49)
	at com.gaia3d.command.model.BatchedProcessModel.run(BatchedProcessModel.java:78)
	at com.gaia3d.command.mago.Mago3DTiler.execute(Mago3DTiler.java:27)
	at com.gaia3d.command.mago.Mago3DTilerMain.main(Mago3DTilerMain.java:55)
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: File does not exist: /workspace/kml/http:/maps.google.com/mapfiles/kml/pushpin/ylw-pushpin.png
	at java.base/java.util.concurrent.FutureTask.report(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.get(Unknown Source)
	at com.gaia3d.process.TilingPipeline.executeThread(TilingPipeline.java:175)
	... 5 more
Caused by: java.lang.RuntimeException: File does not exist: /workspace/kml/http:/maps.google.com/mapfiles/kml/pushpin/ylw-pushpin.png
	at com.gaia3d.converter.assimp.AssimpConverter.load(AssimpConverter.java:57)
	at com.gaia3d.converter.loader.BatchedFileLoader.loadScene(BatchedFileLoader.java:36)
	at com.gaia3d.converter.loader.BatchedFileLoader.loadTileInfo(BatchedFileLoader.java:91)
	at com.gaia3d.process.TilingPipeline.lambda$startPreProcesses$0(TilingPipeline.java:79)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

docker run --rm -v "/home/a/Downloads/road:/workspace" gaia3d/mago-3d-tiler:1.9.0 -it kml -i /workspace/kml/ -o /workspace/tiles -d
How to fix this problem?

**Comment by znkim** [comment]
Hello, @logchen 

There seems to be a bug in the parsing of the KML.
mago-3d-tiler doesn't convert results containing “http” links.
The feature to download data from the HTTP URL has not been yet considered.
It was also reading the image markers.

When converting, I recommend converting to a kml file that contains paths to the only 3D objects.

Thank you.
